---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: public/static
public_path: https://gifted-kare-fa4f68.netlify.app/public/static
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
